[package]
name = "swarmforge-buffers"
version = "0.1.0"
edition = "2024"
description = "Utils to work with byte buffers in librtbit source code"
license = "Apache-2.0"
repository = "https://github.com/TheDancingDeveloper-org/rustTorrent"
readme = "../SWARMFORGE-README.md"
keywords = ["buffers", "bittorrent", "swarmforge"]
categories = ["data-structures", "network-programming"]

[lib]
name = "librtbit_buffers"

[dependencies]
serde = "1"
serde_derive = "1"
clone_to_owned.workspace = true
bytes = "1"

[lints.clippy]
all = { level = "warn", priority = -1 }

[lints.rust]
unused = "warn"
